name = "minus-one-labs"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "minus-one-labs-db"
database_id = "192016a6-1a9b-4f60-a488-309246760c8b"
